name: Test Approvals
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello, world.
